### ISSUE TITLE
[BUG反馈][无害][emc查看器显示不正确]

### ISSUE THREAD

**Issue by soyunxi** [BiggestXuan/EMCWorld#12]
### BUG的表现:
目前阶段：二阶段
使用emc查看器的打开容器消耗
![image](https://user-images.githubusercontent.com/113510593/205785401-8cf4815f-f75d-4bdf-86e9-159fe9132961.png)
实际上消耗
![C9ED@RX3SR1EZ(K_VITRMGY](https://user-images.githubusercontent.com/113510593/205786879-4bf6c9be-229b-44ef-919d-bd22c440fc3b.png)

### 操作环境:

- JAVA版本(jdk-11.0.15.1, jdk1.8.0_311):
- EMC World 版本(0.1.0, 0.2.0):

**Comment by BiggestXuan** [comment]
四舍五入导致，下个版本将保留一位小数。

**Comment by BiggestXuan** [comment]
比想象中麻烦，暂时不修了，后续可能全部向上取整。
