### ISSUE TITLE
记事本

### ISSUE THREAD

**Issue by BiggestXuan** [BiggestXuan/EMCWorld#19]
1.SH的东西还没禁用
2.玩家驯服的实体在受伤交互的时候需要扣玩家emc
3.玩家驯服实体在玩家下线后的交互用dat存储，然后玩家上线后扣玩家emc
4.针对3，制作负emc系统，即锁定emc为0，需要把emc还清后才能是正的
5.玩家点燃的tnt造成伤害/破坏方块扣emc
6.非玩家点燃的tnt热爆花都不接受
7.玩家没emc死的时候会炸装备（用die(DamageSource);）
8.任务给的emc需要增加，完成的时候检测当前队伍的玩家数量，然后平分emc
9.锤子的伤害因操作失误，伤害翻倍了...
10.在面板写上武器强化等级、品质，避免玩家把物品改名后不知道物品真实属性
11.部分装备在平凡词条下生命上限引起的问题
12.能减少玩家生命上限将按百分比计算而不是固定值
13.加个欢乐斗地主同款送豆子功能（
14.法杖的额外消耗直接写面板上，不偷摸的算了
15.加速火把和怀表不能加速收集器和继电器

**Comment by BiggestXuan** [comment]
稍微降低一点emc消耗

**Comment by BiggestXuan** [comment]
个人emc接口和他的材料没有配方

**Comment by ys-yuanshou** [comment]
支持外部服务器开服 加一个卡顿少的物流系统

**Comment by ys-yuanshou** [comment]
为多人添加认领区块的功能 认领区块需要消耗emc 还需要定期上交租金（emc） 最大认领的区块数量需要在任务里消耗emc解锁 一开始不用解锁过多的区块 因为一个可以防止怪物破坏的领地 太过于好获取不太好 主要是一开始给几个区块好让玩家建家 防止其他玩家偷东西 玩家下线后还需不需要交租金我还没想好 万一玩家一上线emc负了寸步难行怎么搞

**Comment by ys-yuanshou** [comment]
希望加入可以重置职业的道具 总会有人选错的

**Comment by ys-yuanshou** [comment]
刷怪希望调整下 其他世界全刷神圣rpg的怪了 还有就是清理一片地 插好火把竟然还刷独眼巨人这种中立怪
