### ISSUE TITLE
[BUG反馈][轻微][RSAutomation无法配置是否启用成型/破坏面板]

### ISSUE THREAD

**Issue by Fanccy315** [BiggestXuan/EMCWorld#23]
### BUG的表现:
右击成型/破坏面板显示"整合包已禁用该方块"

### 复现方法:
1. 在emcworld-common.toml中设置"Enable Refined Storage Automation"为true
2. 重启游戏，进入存档，右击成型/破坏面板

### 操作环境:

- JAVA版本:`openjdk version "11.0.20"`
- EMCWorld 版本:`EMCWorld-1.0.3.jar`

**Comment by BiggestXuan** [comment]
整合包预设内容，为避免科技化占比过高，因此对RS自动化部分进行限制，在WIKI中有提到：
https://www.kancloud.cn/biggest_xuan/emcworld/3172372

**Comment by BiggestXuan** [comment]
这两个面板存在刷物品BUG 因此禁用 后续会进行调整

**Comment by BiggestXuan** [comment]
1.0.4版本启用RS自动化后不再禁用这两个面板。
