### ISSUE TITLE
[BUG反馈][轻微]EMC消失术

### ISSUE THREAD

**Issue by humonia-sys** [BiggestXuan/EMCWorld#3]
# 当捡起在当前GameStage不适用的物品时,会在丢出此物品的同时消耗对应的EMC

- 整合包版本: **0.1**
- 复刻方法: **捡起Unfamiliar Item**
- 危害等级: ***轻微***

**Comment by BiggestXuan** [comment]
已记录，尝试在下个版本修复。

**Comment by BiggestXuan** [comment]
已修复，代码将在0.2.0版本提交。
